=== hyalinne/XMLParser/xmlSAXParser/workspace/skyrim.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://uxmlab.mju.ac.kr/Skyrim" targetNamespace="http://uxmlab.mju.ac.kr/Skyrim" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Skyrim" type="rootType"/>

	<xs:complexType name="rootType">
		<xs:sequence>
			<xs:element name="character" type="characterType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="characterType">
		<xs:sequence>
			<xs:element name="race" type="raceListType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="stat" type="statType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="magic" type="magicListType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="raceListType">
		<xs:sequence>
			<xs:element name="human" type="humanType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="elven" type="elvenType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="beast" type="beastType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="humanType">
		<xs:sequence>
			<xs:element name="nord" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="breton" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="imperial" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="redgard" type="raceType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="elvenType">
		<xs:sequence>
			<xs:element name="dunmer" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="bosmer" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="altmer" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="orc" type="raceType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="beastType">
		<xs:sequence>
			<xs:element name="khajiit" type="raceType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="argonian" type="raceType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="raceType">
		<xs:sequence>
			<xs:element name="race_power" type="powerType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="powerType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="statType">
		<xs:sequence>
			<xs:element name="health" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="magicka" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="stamina" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="magicListType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="desturction" type="magicKindType"/>
				<xs:element name="alternation" type="magicKindType"/>
				<xs:element name="illusiton" type="magicKindType"/>
				<xs:element name="restroration" type="magicKindType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="magicKindType">
		<xs:sequence>
			<xs:element name="novice" type="levelType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="apprentice" type="levelType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="adept" type="levelType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="expert" type="levelType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="master" type="levelType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="levelType">
		<xs:sequence>
			<xs:element name="spray" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="missile" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="rune" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="area_missile" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="cloak" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="heavy_missile" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="wall" type="magicType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="storm" type="magicType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="magicType">
		<xs:sequence>
			<xs:element name="fire" type="elementType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ice" type="elementType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="shock" type="elementType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="elementType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== hyalinne/XMLParser/xmlParser/workspace/Skyrim.xml
<?xml version="1.0" encoding="UTF-8"?>

<Skyrim xmlns="http://uxmlab.mju.ac.kr/Skyrim" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uxmlab.mju.ac.kr/Skyrim ./skyrim.xsd">
  <character>
    <race>
      <human>
        <nord>
		  <race_power type='nord'>Shout of Battle</race_power>
        </nord>
        <breton>
          <race_power type='breton'>Dragon Skin</race_power>
        </breton>
        <imperial>
          <race_power type='imperial'>Voice of Emperor</race_power>
        </imperial>
        <redgard>
          <race_power type='redgard'>Adrenaline</race_power>
        </redgard>
      </human>
      <elven>
        <dunmer>
          <race_power type='dunmer'>Wrath of Ancestor</race_power>
        </dunmer>
        <bosmer>
          <race_power type='bosmer'>Command Animals</race_power>
        </bosmer>
        <altmer>
          <race_power type='altmer'>Highborn</race_power>
        </altmer>
        <orc>
          <race_power type='orc'>Fury of Berserker</race_power>
        </orc>
      </elven>
      <beast>
        <khajiit>
          <race_power type='khajiit'>Night Eyes</race_power>
        </khajiit>
        <argonian>
          <race_power type='argonian'>Histskin</race_power>
        </argonian>
      </beast>
    </race>
    <stat>
      <health>health</health>
      <magicka>magicka</magicka>
      <stamina>stamina</stamina>
    </stat>
    <magic>
      <desturction>
        <novice type='desturction'>
          <spray>
            <fire type='spray'>flame</fire>
            <ice type='spray'>frost</ice>
            <shock type='spray'>lightening</shock>
          </spray>
        </novice>
        <apprentice type='desturction'>
          <missile>
            <fire type='missile'>flame</fire>
            <ice type='missile'>frost</ice>
            <shock type='missile'>lightening</shock>
          </missile>
          <rune>
            <fire type='rune'>Rune</fire>
            <ice type='rune'>Rune</ice>
            <shock type='rune'>Rune</shock>
          </rune>
        </apprentice>
        <adept type='desturction'>
          <area_missile>
            <fire type='area_missile'>fire</fire>
            <ice type='area_missile'>frost</ice>
            <shock type='area_missile'>chain</shock>
          </area_missile>
          <cloak>
            <fire type='cloak'>cloak</fire>
            <ice type='cloak'>cloak</ice>
            <shock type='cloak'>cloak</shock>
          </cloak>
        </adept>
        <expert type='desturction'>
          <heavy_missile>
            <fire type='heavy_missile'>missile</fire>
            <ice type='heavy_missile'>missile</ice>
            <shock type='heavy_missile'>missile</shock>
          </heavy_missile>
          <wall>
            <fire type='wall'>wall</fire>
            <ice type='wall'>wall</ice>
            <shock type='wall'>wall</shock>
          </wall>
        </expert>
        <master type='desturction'>
          <storm>
            <fire type='storm'>storm</fire>
            <ice type='storm'>storm</ice>
            <shock type='storm'>storm</shock>
          </storm>
        </master>
      </desturction>
    </magic>
  </character>
</Skyrim>
